[tool.poetry]
name = "tk-mvp"
version = "0.1.0"
description = ""
authors = ["ziteh <honmonoh@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
